# import, data load

In [1]:
import pandas as pd
import numpy as np
import random
from itertools import combinations, permutations
from numpy import dot
from numpy.linalg import norm

In [2]:
df = pd.read_csv('../../data/model/final!!!!!!!!!!!!!!!!!!!!!!!.csv', index_col=0)
dist_mat = pd.read_csv('../../data/model/distance_matrix_final.csv', index_col=0)
df_food_visit = pd.read_csv('../../data/model/food_with_co2_final.csv', index_col=0)
df_acco_visit = pd.read_csv('../../data/model/stay_tagged.csv')

1곳 관광지 선택 input

In [4]:
user = pd.DataFrame()

user['purpose1'] = np.random.rand(1)
user['purpose2'] = np.random.rand(1)
user['purpose3'] = np.random.rand(1)
user['popularity'] = np.random.rand(1)
user['bbak'] = np.random.rand(1)
user['bab'] = np.random.rand(1)

user['car'] = 1 if np.random.rand(1)[0] > 1/2 else 0

user['day1'] = 0#np.random.randint(12)
user['day2'] = 0#np.random.randint(12)
user['day3'] = 0#np.random.randint(12)
user['day4'] = 0#np.random.randint(12)

user['day'] = 0#np.random.randint(8)

display(user)

,purpose1,purpose2,purpose3,popularity,bbak,bab,car,day1,day2,day3,day4,day
0,0.35809,0.212445,0.093551,0.369125,0.741823,0.989071,1,0,0,0,0,0

2곳 관광지 선택 input

In [10]:
user = pd.DataFrame()

user['purpose1'] = np.random.rand(1)
user['purpose2'] = np.random.rand(1)
user['purpose3'] = np.random.rand(1)
user['popularity'] = np.random.rand(1)
user['bbak'] = np.random.rand(1)
user['bab'] = np.random.rand(1)

user['car'] = 1 if np.random.rand(1)[0] > 1/2 else 0

user['day1'] = 3#np.random.randint(12)
user['day2'] = 3#np.random.randint(12)
user['day3'] = 14#np.random.randint(12)
user['day4'] = 14#np.random.randint(12)

user['day'] = 3#np.random.randint(8)

display(user)

,purpose1,purpose2,purpose3,popularity,bbak,bab,car,day1,day2,day3,day4,day
0,0.739521,0.174801,0.854031,0.405034,0.412335,0.471914,1,3,3,14,14,3

3곳 관광지 선택 input

In [12]:
user = pd.DataFrame()

user['purpose1'] = np.random.rand(1)
user['purpose2'] = np.random.rand(1)
user['purpose3'] = np.random.rand(1)
user['popularity'] = np.random.rand(1)
user['bbak'] = np.random.rand(1)
user['bab'] = np.random.rand(1)

user['car'] = 1 if np.random.rand(1)[0] > 1/2 else 0

user['day1'] = 5#np.random.randint(12)
user['day2'] = 10#np.random.randint(12)
user['day3'] = 16#np.random.randint(12)
user['day4'] = 16#np.random.randint(12)

user['day'] = 5#np.random.randint(8)

display(user)

,purpose1,purpose2,purpose3,popularity,bbak,bab,car,day1,day2,day3,day4,day
0,0.822185,0.674433,0.673675,0.736946,0.874663,0.450491,1,5,10,16,16,5

4곳 관광지 선택 input

In [14]:
user = pd.DataFrame()

user['purpose1'] = np.random.rand(1)
user['purpose2'] = np.random.rand(1)
user['purpose3'] = np.random.rand(1)
user['popularity'] = np.random.rand(1)
user['bbak'] = np.random.rand(1)
user['bab'] = np.random.rand(1)

user['car'] = 1 if np.random.rand(1)[0] > 1/2 else 0

user['day1'] = 1#np.random.randint(12)
user['day2'] = 2#np.random.randint(12)
user['day3'] = 6#np.random.randint(12)
user['day4'] = 7#np.random.randint(12)

user['day'] = 7#np.random.randint(8)

display(user)

,purpose1,purpose2,purpose3,popularity,bbak,bab,car,day1,day2,day3,day4,day
0,0.195443,0.389305,0.234022,0.842017,0.919745,0.51687,1,1,2,6,7,7

model input data 최종형태

In [5]:
display(df)
display(user)

,이름,purpose1,purpose2,purpose3,popularity,co2,loc1,loc2,주변관광지,주변음식점,주변숙박
0,성산일출봉(UNESCO 세계자연유산),0.771565,0.682662,0.948563,0.692564,7.606409,15,13,"['성산일출봉(UNESCO 세계자연유산)', '광치기해변', '우도잠수함(제주씨월드...","['맛나식당', '성산회관', '경미네집(경미휴게소)', '바다의집', '그리운바다...","['아름다운리조트', '플레이스 캠프 제주', '골든튤립 제주 성산호텔', '봄그리..."
1,사려니숲길,0.376859,0.325865,0.345421,0.693147,4.831689,1,0,"['사려니숲길', '제주돌문화공원', '노루생태관찰원', '샤이니숲길', '물찻오름...",[],[]
2,카멜리아힐,0.374966,0.568843,0.391210,0.689060,3.687691,8,4,"['카멜리아힐', '아라고나이트 온천(디아넥스호텔)', '방주교회', '헬로키티아일...","['아뜰리에 제주명월', '숨비나리카페', '창천삼거리식당', '숨비나리', '헬로...","['디아넥스 호텔', '중문훼미리리조트', '서귀포호텔 카라반', '레이크힐스 제주..."
3,협재해수욕장,0.740964,0.488754,0.494228,0.689645,1.639161,5,4,"['협재해수욕장', '한림공원', '금능해수욕장', '비양도', '월령선인장군락지'...","['명랑스낵', '피어22', '협재해녀의집', '앤트러사이트', '수우동', '명...","['inn jeju 인제주 게스트하우스', '객의하우스', '블루하와이리조트', '..."
4,월정리해변,0.625939,0.477449,0.401614,0.687889,1.639161,16,13,"['만장굴', '월정리해변', '월정리 카약체험장', '해맞이해안로', '타보카 월...","['구좌상회', '슬슬슬로우', '민경이네어등포해녀촌', '카페콧수염', '월정리에...","['소풍(월정리)', '동박생이', '여울목게스트하우스(월정리)', '뒹글하우스',..."
...,...,...,...,...,...,...,...,...,...,...,...
853,황금굴(한림공원),0.388605,0.290734,0.555345,0.498158,20.802554,5,4,"['협재해수욕장', '한림공원', '금능해수욕장', '비양도', '월령선인장군락지'...","['명랑스낵', '피어22', '협재해녀의집', '앤트러사이트', '수우동', '명...","['inn jeju 인제주 게스트하우스', '객의하우스', '블루하와이리조트', '..."
854,황우럭만화천국사회적협동조합,0.091287,0.194221,0.206500,0.148139,0.274621,5,4,"['한라산소주공장', '이랜드뮤지엄', '한림항', '한림바다체험마을', '한림해안...","['명랑스낵', '한림칼국수', '협재해녀의집', '앤트러사이트', '수우동', '...","['inn jeju 인제주 게스트하우스', '객의하우스', '켄싱턴리조트 제주 한림..."
855,효명사,0.355257,0.201228,0.306002,0.443579,5.339332,12,9,"['고살리숲길', '효명사', '이승이오름(이승악)', '망장포', '감귤상웨빵 체...","['하례정원', '내창생태카페', '한라성']","['예이츠산장', '뜨레향 펜션', '셋째날', '해뜨는집 (남원)']"
856,후포해변,0.123643,0.029678,0.116400,0.330460,0.188619,2,0,"['최영장군사당', '제주올레 18-1코스', '추자도등대', '나바론절벽', '후...","['추자도중앙식당', '제일식당', '커피앤빵', '오동여식당', 'BBQ치킨 추자...","['나바론민박', '추자도민박', '유심이감성하우스민박', '아름다운펜션민박', '..."
857,휴림,0.255390,0.748590,0.306501,0.545193,0.066487,3,0,"['1100고지습지', '한라산어리목코스', '윗세오름(웃세오름)', '휴림', '...","['보말고을', '다가미 애월점', '윈드스톤']","['올레프로방스', '토토하우스']"

,purpose1,purpose2,purpose3,popularity,bbak,bab,car,day1,day2,day3,day4,day
0,0.35809,0.212445,0.093551,0.369125,0.741823,0.989071,1,0,0,0,0,0

# MODEL
1. 관광지 위치, 인기도를 고려하여 1100개의 관광지 중 일부를 필터링

In [8]:
# def babta(num_tour, num_tour_weight):
#     if num_tour == 2:
#         return [0,1]
#     elif num_tour == 3:
#         return [0,1]
#     elif num_tour == 4:
#         return [0,2]
#     elif num_tour == 5:
#         return [0,2]

In [6]:
def babta(num_tour, num_tour_weight):
    if num_tour == 2:
        return [i+j*num_tour for j in range(num_tour_weight) for i in [0,1]]
    elif num_tour == 3:
        return [i+j*num_tour for j in range(num_tour_weight) for i in [0,1]]
    elif num_tour == 4:
        return [i+j*num_tour for j in range(num_tour_weight) for i in [0,2]]
    elif num_tour == 5:
        return [i+j*num_tour for j in range(num_tour_weight) for i in [0,2]]

In [7]:
def assemble(df, user):
    #총 iter 횟수, filtered_df의 개수, combination의 수를 조절하는 역할
    if user['day'].values[0] in (0, 1):
        epochs = 1 
    elif user['day'].values[0] in (2, 3):
        epochs = 2
    elif user['day'].values[0] in (4, 5):
        epochs = 3
    elif user['day'].values[0] in (6, 7):
        epochs = 4

    # 관광지 주변 식당, 숙소가 없을 때 사용하는 지역별 추천 식당, 숙소
    good_food = {0:'숙성도 노형본관', 1:'고집돌우럭 제주함덕점', 2:'우진해장국', 3:'제주광해 애월', 4:'별돈별 협재해변점', 5:'한림칼국수 제주본점', 6:'판포미인', 7:'미영이네식당', 8:'춘심이네 본점', 9:'삼강식당', 10:'형제도식당', 11:'고집돌우럭 중문점', 12:'공천포식당', 13:'성산가는길', 14:'만덕이네', 15:'가시아방국수', 16:'비자림국수집'}
    good_acco = {0:'섬타임즈제주', 1:'제주조천스위스마을게스트하우스', 2:'섬타임즈제주', 3:'나미송 머무는 곳', 4:'코즈게스트하우스', 5:'inn jeju 인제주 게스트하우스', 6:'틸다하우스', 7:'JAY&CHLOE', 8:'코즈게스트하우스', 9:'나날 게스트하우스', 10:'여행스케치 펜션', 11:'나날 게스트하우스', 12:'르페도라', 13:'메종드오조락', 14:'제주통나무휴양펜션', 15:'메종드오조락', 16:'제주가좋아서 펜션'}
    
    whole_route = ['제주공항']
    print('맑은 제주, 밝은 별 : 친환경 제주 여행 시작 !')
    for epoch in range(epochs):
        #
        if user.bbak.values < 0.3:
            num_tour = 2
        elif user.bbak.values < 0.7:
            num_tour = 3
        else:
            num_tour = 4
            
        if epochs != 3:
            num_tour_weight = int(4/epochs)
            if epochs == 1:
                print('***/DAY 1,2,3,4/***')
            elif epochs == 2:
                print(f'***/DAY {2*epoch+1},{2*epoch+2}/***')
            elif epochs == 4:
                print(f'***/DAY {epoch+1}/***')
        else:
            if epoch != 2:
                print(f'***/DAY {epoch+1}/***')
                num_tour_weight = 1
            else:
                print(f'***/DAY 3,4/***')
                num_tour_weight = 2

        num_tour += user.car.values
        num_tour = num_tour[0]
        num_tour_weighted = num_tour * num_tour_weight
        
        num_day = epoch if epochs != 2 else epoch*2
        daily_loc = user[f'day{num_day+1}'].values[0]
        if user[f'day{num_day+1}'].values[0] in (0, 4, 9, 13):
            filtered_df = df.loc[df['loc2']==daily_loc].loc[df['popularity']>.5].sample(n=22)
        else:
            filtered_df = df.loc[df['loc1']==daily_loc].loc[df['popularity']>.25].sample(n=22)
    
        L = []
        for comb in combinations(filtered_df.index, num_tour_weighted):
            L.append(filtered_df.loc[comb, ['purpose1','purpose2','purpose3','popularity']].sum().values)

        combination = list(combinations(filtered_df.index, num_tour_weighted))
        df_tour = pd.DataFrame(combination)

        M = []
        for idx in df_tour.index:
            M.append(filtered_df.loc[df_tour.loc[idx, :].values, 'co2'].sum())
        df_tour['co2'] = M

        cos_sim = []
        for a in L:
            b = user[['purpose1','purpose2','purpose3','popularity']].values.reshape(4,)
            cos_sim.append(dot(a, b)/(norm(a)*norm(b)))
        df_tour['similarity'] = cos_sim

        df_tour_sorted = df_tour.sort_values(by='similarity', ascending=False)
        recommended_tour = df_tour_sorted.loc[df_tour_sorted['co2']<df_tour.co2.quantile(0.25), [i for i in range(num_tour_weighted)]].iloc[0].values

        dist_list = []
        min_route = 0
        
        if len(recommended_tour)>=8:
            min_route = [i for i in df.loc[recommended_tour, 'loc1'].sort_values().index]
        else:
            for idx, perm in enumerate(permutations(recommended_tour)):
                total_dist = 0
                min_dist = 987654321
                for i in range(len(recommended_tour)-1):
                    total_dist += dist_mat.loc[perm[i], f'{perm[i+1]}']
                    min_dist = min(total_dist, min_dist)
                    if min_dist == total_dist:
                        continue
                    elif min_dist < total_dist:
                        min_route = perm
        
        daily_route = []

        ####### 식당
        flag = 0
        for i, point in enumerate(min_route):
            print('관광 :', df.loc[point, '이름'])
            daily_route.append(df.loc[point, '이름'])
            if i in babta(num_tour, num_tour_weight): #관광끝내고 밥먹을 곳 선택
                food_list = []
                for rests in df.loc[df['이름']==df.loc[point, '이름'], '주변음식점'].apply(lambda x: [y.strip()[1:-1] for y in x[1:-1].split(',')]):
                    for j in rests:
                        food_co2 = df_food_visit.loc[df_food_visit['이름']==j, 'co2_rank'].values
                        food_pop = df_food_visit.loc[df_food_visit['이름']==j, 'pop'].values
                        #print(food_co2, food_pop)
                        #이름으로 검색되는 애들
                        if food_co2.size>0:
                            food_list.append((food_co2[0], food_pop[0], j))
                        #이름으로 검색 안되는 애들
                        else:
                            continue
                if food_list:
                    daily_route.append(sorted([(((1-user.bab.values)*i + user.bab.values*j)[0], k) for i, j, k in food_list], reverse=True)[0][1])
                    if flag == 0:
                        print('점심 :', sorted([(((1-user.bab.values)*i + user.bab.values*j)[0], k) for i, j, k in food_list], reverse=True)[0][1])
                        flag = 1
                    else:
                        print('저녁 :', sorted([(((1-user.bab.values)*i + user.bab.values*j)[0], k) for i, j, k in food_list], reverse=True)[0][1])
                        flag = 0
                else:
                    daily_route.append(f'{good_food[daily_loc]}')
                    if flag == 0:
                        print(f'점심 : {good_food[daily_loc]}')
                        flag = 1
                    else:
                        print(f'저녁 : {good_food[daily_loc]}')
                        flag = 0

        ####### 숙소
        acco_list = []
        for i in df.loc[df['이름']==df.loc[min_route[-1], '이름'], '주변숙박'].apply(lambda x: [y.strip()[1:-1] for y in x[1:-1].split(',')]):
            for j in i:
                acco_sort = df_acco_visit.loc[df_acco_visit['이름']==j, '숙박업종'].values
                if acco_sort.size>0:
                    acco_list.append((acco_sort[0], j))
                else:
                    if '호텔' in j:
                        acco_sort = '호텔'
                    elif ('리조트' in j) or ('콘도' in j):
                        acco_sort = '리조트/콘도'
                    elif ('펜션' in j) or ('민박' in j):
                        acco_sort = '펜션/민박'
                    elif ('모텔' in j) or ('여관' in j):
                        acco_sort = '모텔/여관'
                    elif ('게스트하우스' in j):
                        acco_sort = '게스트하우스'
                    elif ('캠핑' in j) or ('글램핑' in j):
                        acco_sort = '캠핑/글램핑'
                    else:
                        continue
                    acco_list.append((acco_sort, j))
        
        if acco_list == []:
            acco_list.append((-1, -1))
        if user.bbak.values < 0.2:
            recommened_acco = random.choice([j if (i=='호텔') or (i=='리조트/콘도') else '' for i, j in acco_list])
        elif user.bbak.values < 0.8:
            recommened_acco = random.choice([j if (i=='펜션/민박') or (i=='모텔/여관') else '' for i, j in acco_list])
        else:
            recommened_acco = random.choice([j if (i=='게스트하우스') or (i=='캠핑/글램핑') else '' for i, j in acco_list])

        if recommened_acco:
            print('숙소 :', recommened_acco)
            daily_route.append(recommened_acco)
        else:
            print(f'숙소 : {good_acco[daily_loc]}')
            daily_route.append(f'{good_acco[daily_loc]}')
        whole_route.extend(daily_route)
    
    return whole_route

# Output

1곳 관광지 선택 output

In [8]:
assemble(df, user)

맑은 제주, 밝은 별 : 친환경 제주 여행 시작 !
***/DAY 1,2,3,4/***
관광 : 닭머르해안길
점심 : 땅꼬분식 뷔페
관광 : 사려니숲길
관광 : 렛츠런팜제주
저녁 : 교래손칼국수
관광 : 함덕해수욕장
관광 : 제주센트럴파크
관광 : 조천함덕해안도로
점심 : 델문도
관광 : 알작지해변
관광 : 아날로그감귤밭
저녁 : 돈사돈
관광 : 용두암해안도로카페거리
관광 : 어승생
관광 : 제주문예회관
점심 : 우진해장국
관광 : 제주목관아
관광 : 이호테우말등대
저녁 : 돈사돈
관광 : 신비의도로
관광 : 제주별빛누리공원[제한적운영중]
관광 : 산지등대
점심 : 우진해장국
관광 : 이호테우해수욕장
관광 : 9.81 파크
저녁 : 라운지엑스 애월점
관광 : 곽지해수욕장
관광 : 제주승마공원
숙소 : 꽃머채 펜션

['제주공항',
 '닭머르해안길',
 '땅꼬분식 뷔페',
 '사려니숲길',
 '렛츠런팜제주',
 '교래손칼국수',
 '함덕해수욕장',
 '제주센트럴파크',
 '조천함덕해안도로',
 '델문도',
 '알작지해변',
 '아날로그감귤밭',
 '돈사돈',
 '용두암해안도로카페거리',
 '어승생',
 '제주문예회관',
 '제주김만복(만복이네김밥집)',
 '제주목관아',
 '이호테우말등대',
 '돈사돈',
 '신비의도로',
 '제주별빛누리공원[제한적운영중]',
 '산지등대',
 '우진해장국',
 '이호테우해수욕장',
 '9.81 파크',
 '라운지엑스 애월점',
 '곽지해수욕장',
 '제주승마공원',
 '꽃머채 펜션']

2곳 관광지 선택 output

In [11]:
assemble(df, user)

맑은 제주, 밝은 별 : 친환경 제주 여행 시작 !
***/DAY 1,2/***
관광 : 구엄포구
점심 : 제주와이너리
관광 : 고내봉(고내오름,고니오름,망오름)
관광 : 곽지패총
저녁 : 봄날카페
관광 : 자리왓
관광 : 큰노꼬메오름
점심 : 제주광해 애월
관광 : 광령귤나무
관광 : 천아숲길 천아계곡
저녁 : 제주광해 애월
관광 : 수산저수지
숙소 : 하늘만큼땅만큼
***/DAY 3,4/***
관광 : 성읍민속마을
점심 : 만덕이네
관광 : 당케산물(당케포구)
관광 : 개오름
저녁 : 허브올레
관광 : 큰사슴이오름
관광 : 따라비오름
점심 : 카페 보름왓
관광 : 오름터 민속마을
관광 : 제주올레 3코스
저녁 : 돌토고리족욕카페
관광 : 좌보미오름
숙소 : 제주통나무휴양펜션

['제주공항',
 '구엄포구',
 '제주와이너리',
 '고내봉(고내오름,고니오름,망오름)',
 '곽지패총',
 '봄날카페',
 '자리왓',
 '큰노꼬메오름',
 '제주광해 애월',
 '광령귤나무',
 '천아숲길 천아계곡',
 '제주광해 애월',
 '수산저수지',
 '하늘만큼땅만큼',
 '성읍민속마을',
 '만덕이네',
 '당케산물(당케포구)',
 '개오름',
 '허브올레',
 '큰사슴이오름',
 '따라비오름',
 '카페 보름왓',
 '오름터 민속마을',
 '제주올레 3코스',
 '돌토고리족욕카페',
 '좌보미오름',
 '제주통나무휴양펜션']

3곳 관광지 선택 output

In [13]:
assemble(df, user)

맑은 제주, 밝은 별 : 친환경 제주 여행 시작 !
***/DAY 1/***
관광 : 금능포구
점심 : 유람위드북스
관광 : 한림바다체험마을
관광 : 기독교순례길 2코스(순교의길)
저녁 : 피어22
관광 : 금능해수욕장
관광 : 제주돌마을공원
숙소 : inn jeju 인제주 게스트하우스
***/DAY 2/***
관광 : 푸른콩 방주영농조합법인
점심 : 몽키비치클럽 Monkey Beach
관광 : 엉덩물계곡
관광 : 제주올레 8코스
저녁 : 몽키비치클럽 Monkey Beach
관광 : 별내린전망대
관광 : 중문색달해수욕장
숙소 : 여행스케치 펜션
***/DAY 3,4/***
관광 : 제주민속식품
점심 : 카페 보름왓
관광 : 별방진
관광 : 김녕해수욕장
저녁 : 구좌상회
관광 : 김녕해안도로
관광 : 동거문이오름
관광 : 제주올레 20코스
점심 : 구좌상회
관광 : 아부오름
관광 : 스누피가든
저녁 : 천리식당
관광 : 제주 메이 더 호텔 카라반빌리지
관광 : 비자림
숙소 : 제주가좋아서 펜션

['제주공항',
 '금능포구',
 '유람위드북스',
 '한림바다체험마을',
 '기독교순례길 2코스(순교의길)',
 '피어22',
 '금능해수욕장',
 '제주돌마을공원',
 'inn jeju 인제주 게스트하우스',
 '푸른콩 방주영농조합법인',
 '몽키비치클럽 Monkey Beach',
 '엉덩물계곡',
 '제주올레 8코스',
 '몽키비치클럽 Monkey Beach',
 '별내린전망대',
 '중문색달해수욕장',
 '여행스케치 펜션',
 '제주민속식품',
 '제주담',
 '별방진',
 '김녕해수욕장',
 '구좌상회',
 '김녕해안도로',
 '동거문이오름',
 '제주올레 20코스',
 '구좌상회',
 '아부오름',
 '스누피가든',
 '천리식당',
 '제주 메이 더 호텔 카라반빌리지',
 '비자림',
 '제주가좋아서 펜션']

4곳 관광지 선택 output

In [15]:
assemble(df, user)

맑은 제주, 밝은 별 : 친환경 제주 여행 시작 !
***/DAY 1/***
관광 : 함덕야영장
점심 : 델문도
관광 : 제주오름승마랜드
관광 : 사려니숲길
저녁 : 고집돌우럭 제주함덕점
관광 : 제라진 제주오프로드 사파리
관광 : 벨리타
숙소 : 제주조천스위스마을게스트하우스
***/DAY 2/***
관광 : 후포해변
점심 : 커피앤빵
관광 : 제주별빛누리공원[제한적운영중]
관광 : 아날로그감귤밭
저녁 : 돈사돈
관광 : 제주 카카오캠핑
관광 : 제주목관아
숙소 : 섬타임즈제주
***/DAY 3/***
관광 : 제주현대미술관
점심 : 뉴저지카페
관광 : 신창~차귀해안도로
관광 : 저지 예술인 마을
저녁 : 뉴저지카페
관광 : 방림원
관광 : 엉알해안
숙소 : 뿌리게스트하우스
***/DAY 4/***
관광 : 가파도 마라도 정기여객선
점심 : 카페 사우다드
관광 : 케이제주씨워킹
관광 : 섯알오름
저녁 : 헤이브라더
관광 : 송악카트체험장
관광 : 남문지못
숙소 : JAY&CHLOE

['제주공항',
 '함덕야영장',
 '델문도',
 '제주오름승마랜드',
 '사려니숲길',
 '고집돌우럭 제주함덕점',
 '제라진 제주오프로드 사파리',
 '벨리타',
 '제주조천스위스마을게스트하우스',
 '후포해변',
 '커피앤빵',
 '제주별빛누리공원[제한적운영중]',
 '아날로그감귤밭',
 '버터모닝',
 '제주 카카오캠핑',
 '제주목관아',
 '섬타임즈제주',
 '제주현대미술관',
 '뉴저지카페',
 '신창~차귀해안도로',
 '저지 예술인 마을',
 '뉴저지카페',
 '방림원',
 '엉알해안',
 '뿌리게스트하우스',
 '가파도 마라도 정기여객선',
 '카페 사우다드',
 '케이제주씨워킹',
 '섯알오름',
 '헤이브라더',
 '송악카트체험장',
 '남문지못',
 'JAY&CHLOE']